//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.20 at 03:01:00 PM CEST 
//
package com.witbooking.middleware.integration.rategain.model;

import com.witbooking.middleware.utils.serializers.JaxbDateWithoutTimeSerializer;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.Date;

/**
 * <p>Java class for ApplicationControlType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained
 * within this class.
 *
 * <pre>
 * &lt;complexType name="ApplicationControlType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://cgbridge.rategain.com/OTA/2012/05}DayOfWeekGroup"/>
 *       &lt;attGroup ref="{http://cgbridge.rategain.com/OTA/2012/05}DateTimeSpanGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicationControlType")
public class ApplicationControlType {

    @XmlAttribute(name = "Mon")
    protected Boolean mon;
    @XmlAttribute(name = "Tue")
    protected Boolean tue;
    @XmlAttribute(name = "Wed")
    protected Boolean wed;
    @XmlAttribute(name = "Thu")
    protected Boolean thu;
    @XmlAttribute(name = "Fri")
    protected Boolean fri;
    @XmlAttribute(name = "Sat")
    protected Boolean sat;
    @XmlAttribute(name = "Sun")
    protected Boolean sun;
    @XmlAttribute(name = "Start", required = true)
    @XmlSchemaType(name = "date")
    @XmlJavaTypeAdapter(JaxbDateWithoutTimeSerializer.class)
    protected Date start;
    @XmlAttribute(name = "End", required = true)
    @XmlSchemaType(name = "date")
    @XmlJavaTypeAdapter(JaxbDateWithoutTimeSerializer.class)
    protected Date end;
    private static final String ERR_MSG_INVALID_RANGE = "ApplicationControl: Invalid range assigned.";
    private static final String ERR_MSG_NOT_ALL_DAYS  = "ApplicationContorl: All days must be assigned.";

    public ApplicationControlType() {
    }

    public ApplicationControlType(final Date start, final Date end) {
        this.start = start;
        this.end = end;
    }

    /**
     * Verifies if the range given is not null and if its valid. Also checks if
     * any day is given, all days must be given too.
     *
     * @return <code>true</code> if its valid the information given,
     * otherwise <code>false</code>.
     */
    public ErrorType validate() {
        final boolean allDay = mon != null && tue != null && wed != null && thu != null && fri != null && sat != null && sun != null;
        final boolean rangeValid = start != null && end != null && (end.after(start) || end.equals(start));
        
        return rangeValid
                ? anyDay()
                    ? allDay 
                        ? null 
                        : ErrorType.getErrorTypeNoImplementationCodeInvalidValue(ERR_MSG_NOT_ALL_DAYS)
                    : null
                : ErrorType.getErrorTypeNoImplementationCodeInvalidValue(ERR_MSG_INVALID_RANGE);
    }
    
    public boolean anyDay(){
        return  mon != null || tue != null || wed != null || thu != null || fri != null && sat != null && sun != null;
    }

    /**
     * Gets the value of the mon property.
     *
     * @return possible object is {@link Boolean }
     *
     */
    public Boolean isMon() {
        return mon;
    }

    /**
     * Sets the value of the mon property.
     *
     * @param value allowed object is {@link Boolean }
     *
     */
    public void setMon(Boolean value) {
        this.mon = value;
    }

    /**
     * Gets the value of the tue property.
     *
     * @return possible object is {@link Boolean }
     *
     */
    public Boolean isTue() {
        return tue;
    }

    /**
     * Sets the value of the tue property.
     *
     * @param value allowed object is {@link Boolean }
     *
     */
    public void setTue(Boolean value) {
        this.tue = value;
    }

    /**
     * Gets the value of the wed property.
     *
     * @return possible object is {@link Boolean }
     *
     */
    public Boolean isWed() {
        return wed;
    }

    /**
     * Sets the value of the wed property.
     *
     * @param value allowed object is {@link Boolean }
     *
     */
    public void setWed(Boolean value) {
        this.wed = value;
    }

    /**
     * Gets the value of the thu property.
     *
     * @return possible object is {@link Boolean }
     *
     */
    public Boolean isThu() {
        return thu;
    }

    /**
     * Sets the value of the thu property.
     *
     * @param value allowed object is {@link Boolean }
     *
     */
    public void setThu(Boolean value) {
        this.thu = value;
    }

    /**
     * Gets the value of the fri property.
     *
     * @return possible object is {@link Boolean }
     *
     */
    public Boolean isFri() {
        return fri;
    }

    /**
     * Sets the value of the fri property.
     *
     * @param value allowed object is {@link Boolean }
     *
     */
    public void setFri(Boolean value) {
        this.fri = value;
    }

    /**
     * Gets the value of the sat property.
     *
     * @return possible object is {@link Boolean }
     *
     */
    public Boolean isSat() {
        return sat;
    }

    /**
     * Sets the value of the sat property.
     *
     * @param value allowed object is {@link Boolean }
     *
     */
    public void setSat(Boolean value) {
        this.sat = value;
    }

    /**
     * Gets the value of the sun property.
     *
     * @return possible object is {@link Boolean }
     *
     */
    public Boolean isSun() {
        return sun;
    }

    /**
     * Sets the value of the sun property.
     *
     * @param value allowed object is {@link Boolean }
     *
     */
    public void setSun(Boolean value) {
        this.sun = value;
    }

    /**
     * Gets the value of the start property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public Date getStart() {
        return start;
    }

    /**
     * Sets the value of the start property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setStart(Date value) {
        this.start = value;
    }

    /**
     * Gets the value of the end property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public Date getEnd() {
        return end;
    }

    /**
     * Sets the value of the end property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setEnd(Date value) {
        this.end = value;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final ApplicationControlType other = (ApplicationControlType) obj;
        if (this.mon != other.mon && (this.mon == null || !this.mon.equals(other.mon))) {
            return false;
        }
        if (this.tue != other.tue && (this.tue == null || !this.tue.equals(other.tue))) {
            return false;
        }
        if (this.wed != other.wed && (this.wed == null || !this.wed.equals(other.wed))) {
            return false;
        }
        if (this.thu != other.thu && (this.thu == null || !this.thu.equals(other.thu))) {
            return false;
        }
        if (this.fri != other.fri && (this.fri == null || !this.fri.equals(other.fri))) {
            return false;
        }
        if (this.sat != other.sat && (this.sat == null || !this.sat.equals(other.sat))) {
            return false;
        }
        if (this.sun != other.sun && (this.sun == null || !this.sun.equals(other.sun))) {
            return false;
        }
        if (this.start != other.start && (this.start == null || !this.start.equals(other.start))) {
            return false;
        }
        if (this.end != other.end && (this.end == null || !this.end.equals(other.end))) {
            return false;
        }
        return true;
    }
}
