//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.20 at 03:01:00 PM CEST 
//

package com.witbooking.middleware.integration.rategain.model;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for HotelProductsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HotelProductsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HotelProduct" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="ProductReference" type="{http://cgbridge.rategain.com/OTA/2012/05}ProductReferenceType"/>
 *                   &lt;element name="RoomTypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="RateTypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="HotelCode" use="required" type="{http://cgbridge.rategain.com/OTA/2012/05}StringLength1to64" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HotelProductsType", propOrder = {
    "hotelProduct"
})
public class HotelProductsType {

    @XmlElement(name = "HotelProduct", required = true)
    protected List<HotelProduct> hotelProduct;
    @XmlAttribute(name = "HotelCode", required = true)
    protected String hotelCode;

    public HotelProductsType(){}
    public HotelProductsType(List<HotelProduct> hotelProduct,String hotelCode){
        this.hotelProduct = hotelProduct;
        this.hotelCode = hotelCode;
    }

    /**
     * Gets the value of the hotelProduct property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hotelProduct property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHotelProduct().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HotelProductsType.HotelProduct }
     *
     *
     */
    public List<HotelProduct> getHotelProduct() {
        if (hotelProduct == null) {
            hotelProduct = new ArrayList<HotelProduct>();
        }
        return this.hotelProduct;
    }

    /**
     * Gets the value of the hotelCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHotelCode() {
        return hotelCode;
    }

    /**
     * Sets the value of the hotelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHotelCode(String value) {
        this.hotelCode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="ProductReference" type="{http://cgbridge.rategain.com/OTA/2012/05}ProductReferenceType"/>
     *         &lt;element name="RoomTypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="RateTypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static final class HotelProduct {

        @XmlElement(name = "ProductReference", required = true)
        protected ProductReferenceType productReference;
        @XmlElement(name = "RoomTypeName", required = true)
        protected String roomTypeName;
        @XmlElement(name = "RateTypeName", required = true)
        protected String rateTypeName;
        
        public HotelProduct(){}
        
        public HotelProduct(String roomStayCode,String ratePlanCode,String roomStayName,String ratePlanName){
            roomTypeName = roomStayName;
            rateTypeName = ratePlanName;
            productReference = new ProductReferenceType(roomStayCode,ratePlanCode);
        }

        /**
         * Gets the value of the productReference property.
         * 
         * @return
         *     possible object is
         *     {@link ProductReferenceType }
         *     
         */
        public ProductReferenceType getProductReference() {
            return productReference;
        }

        /**
         * Sets the value of the productReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link ProductReferenceType }
         *     
         */
        public void setProductReference(ProductReferenceType value) {
            this.productReference = value;
        }

        /**
         * Gets the value of the roomTypeName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRoomTypeName() {
            return roomTypeName;
        }

        /**
         * Sets the value of the roomTypeName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRoomTypeName(String value) {
            this.roomTypeName = value;
        }

        /**
         * Gets the value of the rateTypeName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRateTypeName() {
            return rateTypeName;
        }

        /**
         * Sets the value of the rateTypeName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRateTypeName(String value) {
            this.rateTypeName = value;
        }

    }

}
