//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.20 at 03:01:00 PM CEST 
//
package com.witbooking.middleware.integration.rategain.model;

import org.apache.log4j.Logger;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * <p>Java class for HotelARIDataType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained
 * within this class.
 *
 * <pre>
 * &lt;complexType name="HotelARIDataType">
 *   &lt;complexContent>
 *     &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProductReference" type="{http://cgbridge.rategain.com/OTA/2012/05}ProductReferenceType"/>
 *         &lt;element name="ApplicationControl" type="{http://cgbridge.rategain.com/OTA/2012/05}ApplicationControlType"/>
 *         &lt;element name="RateAmounts" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Base" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="OccupancyCode" use="required" type="{http://cgbridge.rategain.com/OTA/2012/05}OccupancyCodeType" />
 *                           &lt;attribute name="Amount" use="required" type="{http://cgbridge.rategain.com/OTA/2012/05}Money" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Additional" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="OccupancyCode" use="required" type="{http://cgbridge.rategain.com/OTA/2012/05}OccupancyCodeType" />
 *                           &lt;attribute name="Amount" use="required" type="{http://cgbridge.rategain.com/OTA/2012/05}Money" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="MealPlans" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="MealPlan" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="MealPlanCodeType" use="required" type="{http://cgbridge.rategain.com/OTA/2012/05}MealPlanCodeType" />
 *                                     &lt;attribute name="Included" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                                     &lt;attribute name="Amount" use="required" type="{http://cgbridge.rategain.com/OTA/2012/05}Money" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Discount" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="Amount" type="{http://cgbridge.rategain.com/OTA/2012/05}Money" />
 *                           &lt;attribute name="Percent" type="{http://cgbridge.rategain.com/OTA/2012/05}Percentage" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Currency" type="{http://cgbridge.rategain.com/OTA/2012/05}AlphaLength3" />
 *                 &lt;attribute name="TaxesIncluded" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Availability" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="Master" type="{http://cgbridge.rategain.com/OTA/2012/05}AvailabilityStatusType" />
 *                 &lt;attribute name="Arrival" type="{http://cgbridge.rategain.com/OTA/2012/05}AvailabilityStatusType" />
 *                 &lt;attribute name="Departure" type="{http://cgbridge.rategain.com/OTA/2012/05}AvailabilityStatusType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BookingLimit" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="BaseAllotment" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="ReleaseDays" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *                           &lt;attribute name="Sold" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *                           &lt;attribute name="Allotment" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="TransientAllotment" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="ReleaseDays" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *                           &lt;attribute name="Sold" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *                           &lt;attribute name="Allotment" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/all>
 *                 &lt;attribute name="Sold" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *                 &lt;attribute name="FreeSale" type="{http://cgbridge.rategain.com/OTA/2012/05}OnOffType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BookingRules" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="MinAdvancedBookingOffset" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *                   &lt;element name="MaxAdvancedBookingOffset" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *                   &lt;element name="MinLoSOnArrival" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *                   &lt;element name="MaxLoSOnArrival" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *                   &lt;element name="MinLoSThrough" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *                   &lt;element name="MaxLoSThrough" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ItemIdentifier" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HotelARIDataType", propOrder = {
    "productReference",
    "applicationControl",
    "rateAmounts",
    "availability",
    "bookingLimit",
    "bookingRules",
    "description"
})
public class HotelARIDataType {

    private static final org.apache.log4j.Logger logger = org.apache.log4j.Logger.getLogger(HotelARIDataType.class);
    @XmlElement(name = "ProductReference", required = true)
    protected ProductReferenceType productReference;
    @XmlElement(name = "ApplicationControl", required = true)
    protected ApplicationControlType applicationControl;
    @XmlElement(name = "RateAmounts")
    protected HotelARIDataType.RateAmounts rateAmounts;
    @XmlElement(name = "Availability")
    protected HotelARIDataType.Availability availability;
    @XmlElement(name = "BookingLimit")
    protected HotelARIDataType.BookingLimit bookingLimit;
    @XmlElement(name = "BookingRules")
    protected HotelARIDataType.BookingRules bookingRules;
    @XmlElement(name = "Description")
    protected String description;
    @XmlAttribute(name = "ItemIdentifier")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer itemIdentifier;

    public HotelARIDataType() {
    }

    public HotelARIDataType(final String roomStayTicker, final String ratePlanTicker,
            final Date startDate, final Date endDate, final String currency,
            final OccupancyCodeType occupancyCodeType, final float amount,
            final String mealPlanTicker, final Float discount, final AvailabilityStatusType master,
            final AvailabilityStatusType arrival, final AvailabilityStatusType departure,
            final Integer allotment, final Integer minNotice, final Integer maxNotice,
            final Integer minStay, final Integer maxStay, final String description) {
        productReference = new ProductReferenceType(roomStayTicker, ratePlanTicker);
        applicationControl = new ApplicationControlType(startDate, endDate);
        rateAmounts = new HotelARIDataType.RateAmounts(currency, occupancyCodeType, amount, mealPlanTicker, discount);
        this.availability = new Availability(master, arrival, departure);
        this.bookingLimit = new BookingLimit(allotment);
        this.bookingRules = new BookingRules(minNotice, maxNotice, minStay, maxStay);
        this.description = description;

    }

    /**
     * Gets the value of the productReference property.
     *
     * @return possible object is {@link ProductReferenceType }
     *
     */
    public ProductReferenceType getProductReference() {
        return productReference;
    }

    public String getProductReferenceInvTypeCode() {
        return productReference != null ? productReference.getInvTypeCode() : null;
    }

    public String getProductReferenceRatePlanCode() {
        return productReference != null ? productReference.getRatePlanCode() : null;
    }

    /**
     * Sets the value of the productReference property.
     *
     * @param value allowed object is {@link ProductReferenceType }
     *
     */
    public void setProductReference(ProductReferenceType value) {
        this.productReference = value;
    }

    /**
     * Gets the value of the applicationControl property.
     *
     * @return possible object is {@link ApplicationControlType }
     *
     */
    public ApplicationControlType getApplicationControl() {
        return applicationControl;
    }

    /**
     * Gets the value of the applicationControl property.
     *
     * @return possible object is {@link ApplicationControlType }
     *
     */
    public Date getApplicationControlEndDate() {
        return applicationControl != null ? applicationControl.getEnd() : null;
    }

    /**
     * Gets the value of the applicationControl property.
     *
     * @return possible object is {@link ApplicationControlType }
     *
     */
    public Date getApplicationControlStartDate() {
        return applicationControl != null ? applicationControl.getStart() : null;
    }

    /**
     * Sets the value of the applicationControl property.
     *
     * @param value allowed object is {@link ApplicationControlType }
     *
     */
    public void setApplicationControl(ApplicationControlType value) {
        this.applicationControl = value;
    }

    /**
     * Sets the value of the applicationControl.endDay property.
     *
     * @param value allowed object is {@link ApplicationControlType }
     *
     */
    public void setApplicationControlExtendEndDate(Date value) {
        this.applicationControl.setEnd(value);
    }

    /**
     * Gets the value of the rateAmounts property.
     *
     * @return possible object is {@link HotelARIDataType.RateAmounts }
     *
     */
    public HotelARIDataType.RateAmounts getRateAmounts() {
        return rateAmounts;
    }

    public String getRateAmountsCurrency() {
        return rateAmounts == null ? null : rateAmounts.getCurrency();
    }

    public Float getRateAmountsAmount() {
        return rateAmounts == null
                || rateAmounts.getBase() ==null
                || rateAmounts.getBase().isEmpty()
                || rateAmounts.getBase().get(0) == null
                ? null
                : rateAmounts.getBase().get(0).getAmount();
    }

    /**
     * Sets the value of the rateAmounts property.
     *
     * @param value allowed object is {@link HotelARIDataType.RateAmounts }
     *
     */
    public void setRateAmounts(HotelARIDataType.RateAmounts value) {
        this.rateAmounts = value;
    }

    /**
     * Gets the value of the availability property.
     *
     * @return possible object is {@link HotelARIDataType.Availability }
     *
     */
    public HotelARIDataType.Availability getAvailability() {
        return availability;
    }

    /**
     * Gets the value of the availability master property.
     *
     * @return possible object is {@link HotelARIDataType.Availability }
     *
     */
    public AvailabilityStatusType getAvailabilityMaster() {
        return availability == null ? null : availability.getMaster();
    }

    /**
     * Sets the value of the availability property.
     *
     * @param value allowed object is {@link HotelARIDataType.Availability }
     *
     */
    public void setAvailability(HotelARIDataType.Availability value) {
        this.availability = value;
    }

    /**
     * Gets the value of the bookingLimit property.
     *
     * @return possible object is {@link HotelARIDataType.BookingLimit }
     *
     */
    public HotelARIDataType.BookingLimit getBookingLimit() {
        return bookingLimit;
    }

    /**
     * Gets the value of the release value of TransientAllotment property.
     *
     * @return possible object is {@link HotelARIDataType.BookingLimit }
     *
     */
    public Integer getBookingLimitTransientAllotmentAllotment() {
        return bookingLimit == null
                || bookingLimit.getTransientAllotment() == null
                ? null : bookingLimit.getTransientAllotment().getAllotment();
    }

    /**
     * Gets the value of the bookingLimit property.
     *
     * @return possible object is {@link HotelARIDataType.BookingLimit }
     *
     */
    public OnOffType getBookingLimitFreeSale() {
        return bookingLimit == null ? null : bookingLimit.getFreeSale();
    }

    /**
     * Sets the value of the bookingLimit property.
     *
     * @param value allowed object is {@link HotelARIDataType.BookingLimit }
     *
     */
    public void setBookingLimit(HotelARIDataType.BookingLimit value) {
        this.bookingLimit = value;
    }

    /**
     * Gets the value of the bookingRules property.
     *
     * @return possible object is {@link HotelARIDataType.BookingRules }
     *
     */
    public HotelARIDataType.BookingRules getBookingRules() {
        return bookingRules;
    }

    /**
     * Gets the value of the minAdvancedBookingOffset of bookingRules property.
     *
     * @return possible object is {@link HotelARIDataType.BookingRules }
     *
     */
    public Integer getBookingRulesMinAdvancedBookingOffSet() {
        return bookingRules == null  ? null : bookingRules.getMinAdvancedBookingOffset();
    }

    /**
     * Gets the value of the maxAdvancedBookingOffset of bookingRules property.
     *
     * @return possible object is {@link HotelARIDataType.BookingRules }
     *
     */
    public Integer getBookingRulesMaxAdvancedBookingOffset() {
        return bookingRules == null  ? null : bookingRules.getMaxAdvancedBookingOffset();
    }

    /**
     * Gets the value of the minAdvancedBookingOffset of bookingRules property.
     *
     * @return possible object is {@link HotelARIDataType.BookingRules }
     *
     */
    public Integer getBookingRulesMinLoSOnArrival() {
        return bookingRules == null  ? null : bookingRules.getMinLoSOnArrival();
    }

    /**
     * Gets the value of the maxAdvancedBookingOffset of bookingRules property.
     *
     * @return possible object is {@link HotelARIDataType.BookingRules }
     *
     */
    public Integer getBookingRulesMaxLoSOnArrival() {
        return bookingRules == null  ? null : bookingRules.getMaxLoSOnArrival();
    }

    /**
     * Sets the value of the bookingRules property.
     *
     * @param value allowed object is {@link HotelARIDataType.BookingRules }
     *
     */
    public void setBookingRules(HotelARIDataType.BookingRules value) {
        this.bookingRules = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the itemIdentifier property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public Integer getItemIdentifier() {
        return itemIdentifier;
    }

    /**
     * Sets the value of the itemIdentifier property.
     *
     * @param value allowed object is {@link BigInteger }
     *
     */
    public void setItemIdentifier(Integer value) {
        this.itemIdentifier = value;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final HotelARIDataType other = (HotelARIDataType) obj;
//        logger.debug("ProductReference");
        if (this.productReference != other.productReference && (this.productReference == null || !this.productReference.equals(other.productReference))) {
            return false;
        }
//        if (this.applicationControl != other.applicationControl && (this.applicationControl == null || !this.applicationControl.equals(other.applicationControl))) {
//            return false;
//        }
//        logger.debug("availability");
        if (this.availability != other.availability && (this.availability == null || !this.availability.equals(other.availability))) {
            return false;
        }
//        logger.debug("bookingLimit");
        if (this.bookingLimit != other.bookingLimit && (this.bookingLimit == null || !this.bookingLimit.equals(other.bookingLimit))) {
            return false;
        }
//        logger.debug("bookingRules");
        if (this.bookingRules != other.bookingRules && (this.bookingRules == null || !this.bookingRules.equals(other.bookingRules))) {
            return false;
        }
//        logger.debug("description");
        if ((this.description == null) ? (other.description != null) : !this.description.equals(other.description)) {
            return false;
        }
//        logger.debug("rateAmounts");
        if ((this.rateAmounts == null) ? (other.rateAmounts != null) : !this.rateAmounts.equals(other.rateAmounts)) {
            return false;
        }
        return true;
    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="Master" type="{http://cgbridge.rategain.com/OTA/2012/05}AvailabilityStatusType" />
     *       &lt;attribute name="Arrival" type="{http://cgbridge.rategain.com/OTA/2012/05}AvailabilityStatusType" />
     *       &lt;attribute name="Departure" type="{http://cgbridge.rategain.com/OTA/2012/05}AvailabilityStatusType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Availability {

        @XmlAttribute(name = "Master")
        protected AvailabilityStatusType master;
        @XmlAttribute(name = "Arrival")
        protected AvailabilityStatusType arrival;
        @XmlAttribute(name = "Departure")
        protected AvailabilityStatusType departure;

        private static String getErrMSG(String msg){
            return msg+" property can not be 'Closed'. Unmanaged value.";
        }

        public Availability() {
        }

        public Availability(AvailabilityStatusType master, AvailabilityStatusType arrival, AvailabilityStatusType departure) {
            this.master = master;
            this.arrival = arrival;
            this.departure = departure;
        }

        public ErrorType validate() {
//            return master == null && arrival == null && departure == null;
            if (arrival != null && !arrival.equals(AvailabilityStatusType.OPEN)){
                return ErrorType.getErrorTypeNoImplementationCodeInvalidPropretyCode(getErrMSG("Arrival"));
            }
            if (departure != null && !departure.equals(AvailabilityStatusType.OPEN)){
                return ErrorType.getErrorTypeNoImplementationCodeInvalidPropretyCode(getErrMSG("Departure"));
            }
            return null;
        }

        /**
         * Gets the value of the master property.
         *
         * @return possible object is {@link AvailabilityStatusType }
         *
         */
        public AvailabilityStatusType getMaster() {
            return master;
        }

        /**
         * Sets the value of the master property.
         *
         * @param value allowed object is {@link AvailabilityStatusType }
         *
         */
        public void setMaster(AvailabilityStatusType value) {
            this.master = value;
        }

        /**
         * Gets the value of the arrival property.
         *
         * @return possible object is {@link AvailabilityStatusType }
         *
         */
        public AvailabilityStatusType getArrival() {
            return arrival;
        }

        /**
         * Sets the value of the arrival property.
         *
         * @param value allowed object is {@link AvailabilityStatusType }
         *
         */
        public void setArrival(AvailabilityStatusType value) {
            this.arrival = value;
        }

        /**
         * Gets the value of the departure property.
         *
         * @return possible object is {@link AvailabilityStatusType }
         *
         */
        public AvailabilityStatusType getDeparture() {
            return departure;
        }

        /**
         * Sets the value of the departure property.
         *
         * @param value allowed object is {@link AvailabilityStatusType }
         *
         */
        public void setDeparture(AvailabilityStatusType value) {
            this.departure = value;
        }

        @Override
        public int hashCode() {
            int hash = 7;
            return hash;
        }

        @Override
        public boolean equals(Object obj) {
            if (obj == null) {
                return false;
            }
            if (getClass() != obj.getClass()) {
                return false;
            }
            final Availability other = (Availability) obj;
            if (this.master != other.master) {
                return false;
            }
            if (this.arrival != other.arrival) {
                return false;
            }
            if (this.departure != other.departure) {
                return false;
            }
            return true;
        }
    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="BaseAllotment" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="ReleaseDays" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
     *                 &lt;attribute name="Sold" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
     *                 &lt;attribute name="Allotment" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="TransientAllotment" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="ReleaseDays" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
     *                 &lt;attribute name="Sold" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
     *                 &lt;attribute name="Allotment" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/all>
     *       &lt;attribute name="Sold" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
     *       &lt;attribute name="FreeSale" type="{http://cgbridge.rategain.com/OTA/2012/05}OnOffType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {})
    public static class BookingLimit {

        @XmlElement(name = "BaseAllotment")
        protected HotelARIDataType.BookingLimit.BaseAllotment baseAllotment;
        @XmlElement(name = "TransientAllotment")
        protected HotelARIDataType.BookingLimit.TransientAllotment transientAllotment;
        @XmlAttribute(name = "Sold")
        @XmlSchemaType(name = "unsignedShort")
        protected Integer sold;
        @XmlAttribute(name = "FreeSale")
        protected OnOffType freeSale;
        private static final String ERR_MSG_FREESALE_TRUE = "Freesale can not be true. Unmanaged value.";
//        final String ERR_MSG_TRANSIENT_ALLOTMENT_NULL = "TransientAllotment can not be null.";
        private static final String ERR_MSG_RELEASE_DAYS_VALUE = "ReleaseDay is unmanaged value.";

        public BookingLimit() {
        }

        public BookingLimit(final Integer alloment) {
            this.transientAllotment = new TransientAllotment(alloment);
        }

        public ErrorType validate() {
//            if (transientAllotment == null) {
//                return ErrorType.getErrorTypeProcessingExceptionCodeUnableToProcess(ERR_MSG_TRANSIENT_ALLOTMENT_NULL);
//            }
            if (freeSale != null && !freeSale.equals(OnOffType.OFF)) {
                return ErrorType.getErrorTypeProcessingExceptionCodeUnableToProcess(ERR_MSG_FREESALE_TRUE);
            }
            if (transientAllotment != null && transientAllotment.getReleaseDays() != null) {
                return ErrorType.getErrorTypeProcessingExceptionCodeUnableToProcess(ERR_MSG_RELEASE_DAYS_VALUE);
            }
            return null;
        }

        @Override
        public boolean equals(Object obj) {
            if (obj == null) {
                return false;
            }
            if (getClass() != obj.getClass()) {
                return false;
            }
            final BookingLimit other = (BookingLimit) obj;
            if (this.baseAllotment != other.baseAllotment && (this.baseAllotment == null || !this.baseAllotment.equals(other.baseAllotment))) {
                return false;
            }
            if (this.transientAllotment != other.transientAllotment && (this.transientAllotment == null || !this.transientAllotment.equals(other.transientAllotment))) {
                return false;
            }
            if (this.sold != other.sold && (this.sold == null || !this.sold.equals(other.sold))) {
                return false;
            }
            if (this.freeSale != other.freeSale) {
                return false;
            }
            return true;
        }

        /**
         * Gets the value of the baseAllotment property.
         *
         * @return possible object is
         *     {@link HotelARIDataType.BookingLimit.BaseAllotment }
         *
         */
        public HotelARIDataType.BookingLimit.BaseAllotment getBaseAllotment() {
            return baseAllotment;
        }

        /**
         * Sets the value of the baseAllotment property.
         *
         * @param value allowed object is
         *     {@link HotelARIDataType.BookingLimit.BaseAllotment }
         *
         */
        public void setBaseAllotment(HotelARIDataType.BookingLimit.BaseAllotment value) {
            this.baseAllotment = value;
        }

        /**
         * Gets the value of the transientAllotment property.
         *
         * @return possible object is
         *     {@link HotelARIDataType.BookingLimit.TransientAllotment }
         *
         */
        public HotelARIDataType.BookingLimit.TransientAllotment getTransientAllotment() {
            return transientAllotment;
        }

        /**
         * Sets the value of the transientAllotment property.
         *
         * @param value allowed object is
         *     {@link HotelARIDataType.BookingLimit.TransientAllotment }
         *
         */
        public void setTransientAllotment(HotelARIDataType.BookingLimit.TransientAllotment value) {
            this.transientAllotment = value;
        }

        /**
         * Gets the value of the sold property.
         *
         * @return possible object is {@link Integer }
         *
         */
        public Integer getSold() {
            return sold;
        }

        /**
         * Sets the value of the sold property.
         *
         * @param value allowed object is {@link Integer }
         *
         */
        public void setSold(Integer value) {
            this.sold = value;
        }

        /**
         * Gets the value of the freeSale property.
         *
         * @return possible object is {@link OnOffType }
         *
         */
        public OnOffType getFreeSale() {
            return freeSale;
        }

        /**
         * Sets the value of the freeSale property.
         *
         * @param value allowed object is {@link OnOffType }
         *
         */
        public void setFreeSale(OnOffType value) {
            this.freeSale = value;
        }

        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="ReleaseDays" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
         *       &lt;attribute name="Sold" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
         *       &lt;attribute name="Allotment" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class BaseAllotment {

            @XmlAttribute(name = "ReleaseDays")
            @XmlSchemaType(name = "unsignedShort")
            protected Integer releaseDays;
            @XmlAttribute(name = "Sold")
            @XmlSchemaType(name = "unsignedShort")
            protected Integer sold;
            @XmlAttribute(name = "Allotment", required = true)
            @XmlSchemaType(name = "unsignedShort")
            protected Integer allotment;

            public BaseAllotment() {
            }

            public BaseAllotment(Integer allotment) {
                this.allotment = allotment;
            }

            @Override
            public boolean equals(Object obj) {
                if (obj == null) {
                    return false;
                }
                if (getClass() != obj.getClass()) {
                    return false;
                }
                final BaseAllotment other = (BaseAllotment) obj;
                if (this.releaseDays != other.releaseDays && (this.releaseDays == null || !this.releaseDays.equals(other.releaseDays))) {
                    return false;
                }
                if (this.sold != other.sold && (this.sold == null || !this.sold.equals(other.sold))) {
                    return false;
                }
                if (this.allotment != other.allotment) {
                    return false;
                }
                return true;
            }

            /**
             * Gets the value of the releaseDays property.
             *
             * @return possible object is {@link Integer }
             *
             */
            public Integer getReleaseDays() {
                return releaseDays;
            }

            /**
             * Sets the value of the releaseDays property.
             *
             * @param value allowed object is {@link Integer }
             *
             */
            public void setReleaseDays(Integer value) {
                this.releaseDays = value;
            }

            /**
             * Gets the value of the sold property.
             *
             * @return possible object is {@link Integer }
             *
             */
            public Integer getSold() {
                return sold;
            }

            /**
             * Sets the value of the sold property.
             *
             * @param value allowed object is {@link Integer }
             *
             */
            public void setSold(Integer value) {
                this.sold = value;
            }

            /**
             * Gets the value of the allotment property.
             *
             */
            public Integer getAllotment() {
                return allotment;
            }

            /**
             * Sets the value of the allotment property.
             *
             */
            public void setAllotment(int value) {
                this.allotment = value;
            }
        }

        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="ReleaseDays" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
         *       &lt;attribute name="Sold" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
         *       &lt;attribute name="Allotment" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class TransientAllotment {

            @XmlAttribute(name = "ReleaseDays")
            @XmlSchemaType(name = "unsignedShort")
            protected Integer releaseDays;
            @XmlAttribute(name = "Sold")
            @XmlSchemaType(name = "unsignedShort")
            protected Integer sold;
            @XmlAttribute(name = "Allotment", required = true)
            @XmlSchemaType(name = "unsignedShort")
            protected Integer allotment;

            public TransientAllotment() {}

            public TransientAllotment(Integer allotment) {
                this.allotment = allotment;
            }

            @Override
            public boolean equals(Object obj) {
                if (obj == null) {
                    return false;
                }
                if (getClass() != obj.getClass()) {
                    return false;
                }
                final TransientAllotment other = (TransientAllotment) obj;
                if (this.releaseDays != other.releaseDays && (this.releaseDays == null || !this.releaseDays.equals(other.releaseDays))) {
                    return false;
                }
                if (this.sold != other.sold && (this.sold == null || !this.sold.equals(other.sold))) {
                    return false;
                }
                if (this.allotment != other.allotment) {
                    return false;
                }
                return true;
            }

            /**
             * Gets the value of the releaseDays property.
             *
             * @return possible object is {@link Integer }
             *
             */
            public Integer getReleaseDays() {
                return releaseDays;
            }

            /**
             * Sets the value of the releaseDays property.
             *
             * @param value allowed object is {@link Integer }
             *
             */
            public void setReleaseDays(Integer value) {
                this.releaseDays = value;
            }

            /**
             * Gets the value of the sold property.
             *
             * @return possible object is {@link Integer }
             *
             */
            public Integer getSold() {
                return sold;
            }

            /**
             * Sets the value of the sold property.
             *
             * @param value allowed object is {@link Integer }
             *
             */
            public void setSold(Integer value) {
                this.sold = value;
            }

            /**
             * Gets the value of the allotment property.
             *
             */
            public Integer getAllotment() {
                return allotment;
            }

            /**
             * Sets the value of the allotment property.
             *
             */
            public void setAllotment(int value) {
                this.allotment = value;
            }
        }
    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="MinAdvancedBookingOffset" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
     *         &lt;element name="MaxAdvancedBookingOffset" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
     *         &lt;element name="MinLoSOnArrival" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
     *         &lt;element name="MaxLoSOnArrival" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
     *         &lt;element name="MinLoSThrough" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
     *         &lt;element name="MaxLoSThrough" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {})
    public static class BookingRules {

        @XmlElement(name = "MinAdvancedBookingOffset")
        @XmlSchemaType(name = "unsignedShort")
        protected Integer minAdvancedBookingOffset;
        @XmlElement(name = "MaxAdvancedBookingOffset")
        @XmlSchemaType(name = "unsignedShort")
        protected Integer maxAdvancedBookingOffset;
        @XmlElement(name = "MinLoSOnArrival")
        @XmlSchemaType(name = "unsignedShort")
        protected Integer minLoSOnArrival;
        @XmlElement(name = "MaxLoSOnArrival")
        @XmlSchemaType(name = "unsignedShort")
        protected Integer maxLoSOnArrival;
        @XmlElement(name = "MinLoSThrough")
        @XmlSchemaType(name = "unsignedShort")
        protected Integer minLoSThrough;
        @XmlElement(name = "MaxLoSThrough")
        @XmlSchemaType(name = "unsignedShort")
        protected Integer maxLoSThrough;

        private static final String getMSG(final String msg){
            return msg+" is an unmanaged property. Should be null.";
        }
        public BookingRules() {
        }

        public BookingRules(Integer minAdvancedBookingOffset, Integer maxAdvancedBookingOffset, Integer minLoSOnArrival, Integer maxLoSOnArrival) {
            this.minAdvancedBookingOffset = minAdvancedBookingOffset;
            this.maxAdvancedBookingOffset = maxAdvancedBookingOffset;
            this.minLoSOnArrival = minLoSOnArrival;
            this.maxLoSOnArrival = maxLoSOnArrival;
        }

        public ErrorType validate() {
            if (minLoSThrough != null){
                return ErrorType.getErrorTypeNoImplementationCodeInvalidValue(getMSG("minLoSThrough"));
            }
            if (maxLoSThrough != null){
                return ErrorType.getErrorTypeNoImplementationCodeInvalidValue(getMSG("maxLoSThrough"));
            }
            return null;
        }

        @Override
        public boolean equals(Object obj) {
            if (obj == null) {
                return false;
            }
            if (getClass() != obj.getClass()) {
                return false;
            }
            final BookingRules other = (BookingRules) obj;
            if (this.minAdvancedBookingOffset != other.minAdvancedBookingOffset && (this.minAdvancedBookingOffset == null || !this.minAdvancedBookingOffset.equals(other.minAdvancedBookingOffset))) {
                return false;
            }
            if (this.maxAdvancedBookingOffset != other.maxAdvancedBookingOffset && (this.maxAdvancedBookingOffset == null || !this.maxAdvancedBookingOffset.equals(other.maxAdvancedBookingOffset))) {
                return false;
            }
            if (this.minLoSOnArrival != other.minLoSOnArrival && (this.minLoSOnArrival == null || !this.minLoSOnArrival.equals(other.minLoSOnArrival))) {
                return false;
            }
            if (this.maxLoSOnArrival != other.maxLoSOnArrival && (this.maxLoSOnArrival == null || !this.maxLoSOnArrival.equals(other.maxLoSOnArrival))) {
                return false;
            }
            if (this.minLoSThrough != other.minLoSThrough && (this.minLoSThrough == null || !this.minLoSThrough.equals(other.minLoSThrough))) {
                return false;
            }
            if (this.maxLoSThrough != other.maxLoSThrough && (this.maxLoSThrough == null || !this.maxLoSThrough.equals(other.maxLoSThrough))) {
                return false;
            }
            return true;
        }

        /**
         * Gets the value of the minAdvancedBookingOffset property.
         *
         * @return possible object is {@link Integer }
         *
         */
        public Integer getMinAdvancedBookingOffset() {
            return minAdvancedBookingOffset;
        }

        /**
         * Sets the value of the minAdvancedBookingOffset property.
         *
         * @param value allowed object is {@link Integer }
         *
         */
        public void setMinAdvancedBookingOffset(Integer value) {
            this.minAdvancedBookingOffset = value;
        }

        /**
         * Gets the value of the maxAdvancedBookingOffset property.
         *
         * @return possible object is {@link Integer }
         *
         */
        public Integer getMaxAdvancedBookingOffset() {
            return maxAdvancedBookingOffset;
        }

        /**
         * Sets the value of the maxAdvancedBookingOffset property.
         *
         * @param value allowed object is {@link Integer }
         *
         */
        public void setMaxAdvancedBookingOffset(Integer value) {
            this.maxAdvancedBookingOffset = value;
        }

        /**
         * Gets the value of the minLoSOnArrival property.
         *
         * @return possible object is {@link Integer }
         *
         */
        public Integer getMinLoSOnArrival() {
            return minLoSOnArrival;
        }

        /**
         * Sets the value of the minLoSOnArrival property.
         *
         * @param value allowed object is {@link Integer }
         *
         */
        public void setMinLoSOnArrival(Integer value) {
            this.minLoSOnArrival = value;
        }

        /**
         * Gets the value of the maxLoSOnArrival property.
         *
         * @return possible object is {@link Integer }
         *
         */
        public Integer getMaxLoSOnArrival() {
            return maxLoSOnArrival;
        }

        /**
         * Sets the value of the maxLoSOnArrival property.
         *
         * @param value allowed object is {@link Integer }
         *
         */
        public void setMaxLoSOnArrival(Integer value) {
            this.maxLoSOnArrival = value;
        }

        /**
         * Gets the value of the minLoSThrough property.
         *
         * @return possible object is {@link Integer }
         *
         */
        public Integer getMinLoSThrough() {
            return minLoSThrough;
        }

        /**
         * Sets the value of the minLoSThrough property.
         *
         * @param value allowed object is {@link Integer }
         *
         */
        public void setMinLoSThrough(Integer value) {
            this.minLoSThrough = value;
        }

        /**
         * Gets the value of the maxLoSThrough property.
         *
         * @return possible object is {@link Integer }
         *
         */
        public Integer getMaxLoSThrough() {
            return maxLoSThrough;
        }

        /**
         * Sets the value of the maxLoSThrough property.
         *
         * @param value allowed object is {@link Integer }
         *
         */
        public void setMaxLoSThrough(Integer value) {
            this.maxLoSThrough = value;
        }
    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Base" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="OccupancyCode" use="required" type="{http://cgbridge.rategain.com/OTA/2012/05}OccupancyCodeType" />
     *                 &lt;attribute name="Amount" use="required" type="{http://cgbridge.rategain.com/OTA/2012/05}Money" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Additional" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="OccupancyCode" use="required" type="{http://cgbridge.rategain.com/OTA/2012/05}OccupancyCodeType" />
     *                 &lt;attribute name="Amount" use="required" type="{http://cgbridge.rategain.com/OTA/2012/05}Money" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="MealPlans" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="MealPlan" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="MealPlanCodeType" use="required" type="{http://cgbridge.rategain.com/OTA/2012/05}MealPlanCodeType" />
     *                           &lt;attribute name="Included" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                           &lt;attribute name="Amount" use="required" type="{http://cgbridge.rategain.com/OTA/2012/05}Money" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Discount" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="Amount" type="{http://cgbridge.rategain.com/OTA/2012/05}Money" />
     *                 &lt;attribute name="Percent" type="{http://cgbridge.rategain.com/OTA/2012/05}Percentage" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="Currency" type="{http://cgbridge.rategain.com/OTA/2012/05}AlphaLength3" />
     *       &lt;attribute name="TaxesIncluded" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "base",
        "additional",
        "mealPlans",
        "discount"
    })
    public static class RateAmounts {

        @XmlElement(name = "Base")
        protected List<Base> base = new ArrayList<Base>();
        @XmlElement(name = "Additional")
        protected List<Additional> additional;
        @XmlElement(name = "MealPlans")
        protected HotelARIDataType.RateAmounts.MealPlans mealPlans;
        @XmlElement(name = "Discount")
        protected HotelARIDataType.RateAmounts.Discount discount;
        @XmlAttribute(name = "Currency")
        protected String currency;
        @XmlAttribute(name = "TaxesIncluded")
        protected Boolean taxesIncluded;
        private static final String ERR_MSG_DISCOUNT_VALUE = "Discount is an unmanaged value.";
        private static final String ERR_MSG_ADDITIONAL_VALUE = "Additionals are an unmanaged value.";
        private static final String ERR_MSG_AMOUNT_VALUE = "Amount can not be null.";
        private static final String ERR_MSG_OCCUPANCY_CODE_INVALID = "Occupancy code have an unmanaged value. Occupancy code manage is SR.";
        private static final String ERR_MSG_BASE_LIST_INVALID = "Base list have more than 1 entry. Occupancy code manage is only SR.";

        public RateAmounts(final String currency, final OccupancyCodeType occupancyCodeType,
                final float amount, final String mealPlanTicker, final Float discount) {
            this.currency = currency;
            this.base.add(new Base(occupancyCodeType, amount));
            this.mealPlans = new MealPlans(mealPlanTicker);
            if (discount != null && discount > 0) {
                this.discount = new Discount(discount);
            }
        }

        public RateAmounts() {
        }

        @Override
        public int hashCode() {
            int hash = 3;
            return hash;
        }

        @Override
        public boolean equals(Object obj) {
            if (obj == null) {
                return false;
            }
            if (getClass() != obj.getClass()) {
                return false;
            }
            final RateAmounts other = (RateAmounts) obj;
//            logger.debug("base");
            if (this.base != other.base && (this.base == null || !this.base.equals(other.base))) {
                return false;
            }
//            logger.debug("additional");
            if (this.additional != other.additional && (this.additional == null || !this.additional.equals(other.additional))) {
                return false;
            }
//            logger.debug("mealPlans");
            if (this.mealPlans != other.mealPlans && (this.mealPlans == null || !this.mealPlans.equals(other.mealPlans))) {
                return false;
            }
//            logger.debug("discount");
            if (this.discount != other.discount && (this.discount == null || !this.discount.equals(other.discount))) {
                return false;
            }
//            logger.debug("currency");
            if ((this.currency == null) ? (other.currency != null) : !this.currency.equals(other.currency)) {
                return false;
            }
//            logger.debug("taxesIncluded");
            if (this.taxesIncluded != other.taxesIncluded && (this.taxesIncluded == null || !this.taxesIncluded.equals(other.taxesIncluded))) {
                return false;
            }
            return true;
        }



        public ErrorType validate() {
//            if (base == null || base.isEmpty()) {
//                return INVALIDATE;
//            }
//            final Iterator<Base> iteratorBase = base.iterator();
            if (base != null && !base.isEmpty()) {
                if (base.size() > 1) {
                    return ErrorType.getErrorTypeProcessingExceptionCodeUnableToProcess(ERR_MSG_BASE_LIST_INVALID);
                } else {
                    final Base baseItem = base.get(0);
                    if (baseItem != null) {
                        if (baseItem.getOccupancyCode() == null && baseItem.getAmount() == null){

                        }
                        else if (baseItem.getOccupancyCode() != null && !baseItem.getOccupancyCode().equals(OccupancyCodeType.SR)) {
                            return ErrorType.getErrorTypeProcessingExceptionCodeUnableToProcess(ERR_MSG_OCCUPANCY_CODE_INVALID);
                        }
                        else if (baseItem.getAmount() == null) {
                            return ErrorType.getErrorTypeNoImplementationCodeInvalidValue(ERR_MSG_AMOUNT_VALUE);
                        }
                    }
                }
            }
            if (discount != null && (discount.getAmount() != null || discount.getPercent() != null)) {
                return ErrorType.getErrorTypeProcessingExceptionCodeUnableToProcess(ERR_MSG_DISCOUNT_VALUE);
            }
            if (additional !=null){
                return ErrorType.getErrorTypeProcessingExceptionCodeUnableToProcess(ERR_MSG_ADDITIONAL_VALUE);
            }
            return null;
        }

        /**
         * Gets the value of the baseItem property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the baseItem property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBase().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HotelARIDataType.RateAmounts.Base }
         *
         *
         */
        public List<Base> getBase() {
            if (base == null) {
                base = new ArrayList<Base>();
            }
            return this.base;
        }

        /**
         * Gets the value of the additional property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the additional property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAdditional().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HotelARIDataType.RateAmounts.Additional }
         *
         *
         */
        public List<Additional> getAdditional() {
            if (additional == null) {
                additional = new ArrayList<Additional>();
            }
            return this.additional;
        }

        /**
         * Gets the value of the mealPlans property.
         *
         * @return possible object is
         *     {@link HotelARIDataType.RateAmounts.MealPlans }
         *
         */
        public HotelARIDataType.RateAmounts.MealPlans getMealPlans() {
            return mealPlans;
        }

        /**
         * Sets the value of the mealPlans property.
         *
         * @param value allowed object is
         *     {@link HotelARIDataType.RateAmounts.MealPlans }
         *
         */
        public void setMealPlans(HotelARIDataType.RateAmounts.MealPlans value) {
            this.mealPlans = value;
        }

        /**
         * Gets the value of the discount property.
         *
         * @return possible object is
         *     {@link HotelARIDataType.RateAmounts.Discount }
         *
         */
        public HotelARIDataType.RateAmounts.Discount getDiscount() {
            return discount;
        }

        /**
         * Sets the value of the discount property.
         *
         * @param value allowed object is
         *     {@link HotelARIDataType.RateAmounts.Discount }
         *
         */
        public void setDiscount(HotelARIDataType.RateAmounts.Discount value) {
            this.discount = value;
        }

        /**
         * Gets the value of the currency property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getCurrency() {
            return currency;
        }

        /**
         * Sets the value of the currency property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setCurrency(String value) {
            this.currency = value;
        }

        /**
         * Gets the value of the taxesIncluded property.
         *
         * @return possible object is {@link Boolean }
         *
         */
        public Boolean isTaxesIncluded() {
            return taxesIncluded;
        }

        /**
         * Sets the value of the taxesIncluded property.
         *
         * @param value allowed object is {@link Boolean }
         *
         */
        public void setTaxesIncluded(Boolean value) {
            this.taxesIncluded = value;
        }

        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="OccupancyCode" use="required" type="{http://cgbridge.rategain.com/OTA/2012/05}OccupancyCodeType" />
         *       &lt;attribute name="Amount" use="required" type="{http://cgbridge.rategain.com/OTA/2012/05}Money" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Additional {

            @XmlAttribute(name = "OccupancyCode", required = true)
            protected OccupancyCodeType occupancyCode;
            @XmlAttribute(name = "Amount", required = true)
            protected BigDecimal amount;

            @Override
            public int hashCode() {
                int hash = 7;
                return hash;
            }

            @Override
            public boolean equals(Object obj) {
                if (obj == null) {
                    return false;
                }
                if (getClass() != obj.getClass()) {
                    return false;
                }
                final Additional other = (Additional) obj;
                if (this.occupancyCode != other.occupancyCode) {
                    return false;
                }
                if (this.amount != other.amount && (this.amount == null || !this.amount.equals(other.amount))) {
                    return false;
                }
                return true;
            }

            /**
             * Gets the value of the occupancyCode property.
             *
             * @return possible object is {@link OccupancyCodeType }
             *
             */
            public OccupancyCodeType getOccupancyCode() {
                return occupancyCode;
            }

            /**
             * Sets the value of the occupancyCode property.
             *
             * @param value allowed object is {@link OccupancyCodeType }
             *
             */
            public void setOccupancyCode(OccupancyCodeType value) {
                this.occupancyCode = value;
            }

            /**
             * Gets the value of the amount property.
             *
             * @return possible object is {@link BigDecimal }
             *
             */
            public BigDecimal getAmount() {
                return amount;
            }

            /**
             * Sets the value of the amount property.
             *
             * @param value allowed object is {@link BigDecimal }
             *
             */
            public void setAmount(BigDecimal value) {
                this.amount = value;
            }
        }

        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="OccupancyCode" use="required" type="{http://cgbridge.rategain.com/OTA/2012/05}OccupancyCodeType" />
         *       &lt;attribute name="Amount" use="required" type="{http://cgbridge.rategain.com/OTA/2012/05}Money" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Base {

            @XmlAttribute(name = "OccupancyCode", required = true)
            protected OccupancyCodeType occupancyCode;
            @XmlAttribute(name = "Amount", required = true)
            protected Float amount;

            public Base() {
            }

            public Base(OccupancyCodeType occupancyCode, Float amount) {
                this.occupancyCode = occupancyCode;
                this.amount = amount;
            }

            /**
             * Gets the value of the occupancyCode property.
             *
             * @return possible object is {@link OccupancyCodeType }
             *
             */
            public OccupancyCodeType getOccupancyCode() {
                return occupancyCode;
            }

            /**
             * Sets the value of the occupancyCode property.
             *
             * @param value allowed object is {@link OccupancyCodeType }
             *
             */
            public void setOccupancyCode(OccupancyCodeType value) {
                this.occupancyCode = value;
            }

            /**
             * Gets the value of the amount property.
             *
             * @return possible object is {@link BigDecimal }
             *
             */
            public Float getAmount() {
                return amount;
            }

            /**
             * Sets the value of the amount property.
             *
             * @param value allowed object is {@link BigDecimal }
             *
             */
            public void setAmount(Float value) {
                this.amount = value;
            }

            @Override
            public int hashCode() {
                int hash = 5;
                return hash;
            }

            @Override
            public boolean equals(Object obj) {
                if (obj == null) {
                    return false;
                }
                if (getClass() != obj.getClass()) {
                    return false;
                }
                final Base other = (Base) obj;
                if (this.occupancyCode != other.occupancyCode) {
                    return false;
                }
                if (this.amount != other.amount && (this.amount == null || !this.amount.equals(other.amount))) {
                    return false;
                }
                return true;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="Amount" type="{http://cgbridge.rategain.com/OTA/2012/05}Money" />
         *       &lt;attribute name="Percent" type="{http://cgbridge.rategain.com/OTA/2012/05}Percentage" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Discount {

            @XmlAttribute(name = "Amount")
            protected Float amount;
            @XmlAttribute(name = "Percent")
            protected Float percent;

            public Discount() {
            }

            @Override
            public boolean equals(Object obj) {
                if (obj == null) {
                    return false;
                }
                if (getClass() != obj.getClass()) {
                    return false;
                }
                final Discount other = (Discount) obj;
                if (this.amount != other.amount && (this.amount == null || !this.amount.equals(other.amount))) {
                    return false;
                }
                if (this.percent != other.percent && (this.percent == null || !this.percent.equals(other.percent))) {
                    return false;
                }
                return true;
            }



            public Discount(Float amount) {
                this.amount = amount;
            }

            /**
             * Gets the value of the amount property.
             *
             * @return possible object is {@link BigDecimal }
             *
             */
            public Float getAmount() {
                return amount;
            }

            /**
             * Sets the value of the amount property.
             *
             * @param value allowed object is {@link BigDecimal }
             *
             */
            public void setAmount(Float value) {
                this.amount = value;
            }

            /**
             * Gets the value of the percent property.
             *
             * @return possible object is {@link BigDecimal }
             *
             */
            public Float getPercent() {
                return percent;
            }

            /**
             * Sets the value of the percent property.
             *
             * @param value allowed object is {@link BigDecimal }
             *
             */
            public void setPercent(Float value) {
                this.percent = value;
            }
        }

        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="MealPlan" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="MealPlanCodeType" use="required" type="{http://cgbridge.rategain.com/OTA/2012/05}MealPlanCodeType" />
         *                 &lt;attribute name="Included" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *                 &lt;attribute name="Amount" use="required" type="{http://cgbridge.rategain.com/OTA/2012/05}Money" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "mealPlan"
        })
        public static class MealPlans {

            @XmlElement(name = "MealPlan", required = true)
            protected List<MealPlan> mealPlan = new ArrayList<MealPlan>();

            public MealPlans() {
            }

            public MealPlans(String mealPlan) {
                this.mealPlan.add(new MealPlan(mealPlan));
            }


            @Override
            public boolean equals(Object obj) {
                if (obj == null) {
                    return false;
                }
                if (getClass() != obj.getClass()) {
                    return false;
                }
                final MealPlans other = (MealPlans) obj;
                if (this.mealPlan != other.mealPlan && (this.mealPlan == null || !this.mealPlan.equals(other.mealPlan))) {
                    return false;
                }
                return true;
            }

            /**
             * Gets the value of the mealPlan property.
             *
             * <p>
             * This accessor method returns a reference to the live list, not a
             * snapshot. Therefore any modification you make to the returned
             * list will be present inside the JAXB object. This is why there is
             * not a
             * <CODE>set</CODE> method for the mealPlan property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getMealPlan().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link HotelARIDataType.RateAmounts.MealPlans.MealPlan }
             *
             *
             */
            public List<MealPlan> getMealPlan() {
                if (mealPlan == null) {
                    mealPlan = new ArrayList<MealPlan>();
                }
                return this.mealPlan;
            }

            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content
             * contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction baseItem="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="MealPlanCodeType" use="required" type="{http://cgbridge.rategain.com/OTA/2012/05}MealPlanCodeType" />
             *       &lt;attribute name="Included" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
             *       &lt;attribute name="Amount" use="required" type="{http://cgbridge.rategain.com/OTA/2012/05}Money" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class MealPlan {

                private static final Logger logger = Logger.getLogger(MealPlan.class);
                @XmlAttribute(name = "MealPlanCode", required = true)
                protected MealPlanCodeType mealPlanCode;
                @XmlAttribute(name = "Included", required = true)
                protected final Boolean included = true;
                @XmlAttribute(name = "Amount", required = true)
                protected final Float amount = (float) 0;

                public MealPlan() {
                }

                public MealPlan(String mealPlanTicker) {
                    if (mealPlanTicker != null) {
                        if (mealPlanTicker.contains("PC") || mealPlanTicker.contains("TI")) {
                            this.mealPlanCode = MealPlanCodeType.ALL_INCLUSIVE;
                        } else if (mealPlanTicker.contains("SA")) {
                            this.mealPlanCode = MealPlanCodeType.ROOM_ONLY;
                        } else if (mealPlanTicker.contains("HD")) {
                            this.mealPlanCode = MealPlanCodeType.BREAKFAST;
                        } else if (mealPlanTicker.contains("MP")) {
                            this.mealPlanCode = MealPlanCodeType.DINNED_BED_AND_BREAKFAST_PLAN;
                        } else {
                            this.mealPlanCode = MealPlanCodeType.MODIFIED;
                        }
                    }
                }

                public MealPlan(MealPlanCodeType mealPlanCode) {
                    this.mealPlanCode = mealPlanCode;
                }

                @Override
                public int hashCode() {
                    int hash = 5;
                    return hash;
                }

                @Override
                public boolean equals(Object obj) {
                    if (obj == null) {
                        return false;
                    }
                    if (getClass() != obj.getClass()) {
                        return false;
                    }
                    final MealPlan other = (MealPlan) obj;
                    if (this.mealPlanCode != other.mealPlanCode) {
                        return false;
                    }
                    if (this.included != other.included && (this.included == null || !this.included.equals(other.included))) {
                        return false;
                    }
                    if (this.amount != other.amount && (this.amount == null || !this.amount.equals(other.amount))) {
                        return false;
                    }
                    return true;
                }
                

                @XmlType(name = "MealPlanCodeType")
                @XmlEnum
                public static enum MealPlanCodeType {

                    @XmlEnumValue("1")
                    ALL_INCLUSIVE(1),
                    @XmlEnumValue("14")
                    ROOM_ONLY(14),
                    @XmlEnumValue("17")
                    DINNED_BED_AND_BREAKFAST_PLAN(17),
                    @XmlEnumValue("19")
                    BREAKFAST(19),
                    @XmlEnumValue("20")
                    MODIFIED(20);
                    private final int value;

                    private MealPlanCodeType(final int mealPlanCode) {
                        this.value = mealPlanCode;
                    }

                    public String value() {
                        return value + "";
                    }
                }

                /**
                 * Gets the value of the mealPlanCode property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public MealPlanCodeType getMealPlanCode() {
                    return mealPlanCode;
                }

                /**
                 * Sets the value of the mealPlanCode property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setMealPlanCode(final MealPlanCodeType value) {
                    this.mealPlanCode = value;
                }

                /**
                 * Gets the value of the included property.
                 *
                 */
                public boolean isIncluded() {
                    return included;
                }

                /**
                 * Gets the value of the amount property.
                 *
                 * @return possible object is {@link BigDecimal }
                 *
                 */
                public Float getAmount() {
                    return amount;
                }
            }
        }
    }
}
