//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.20 at 03:01:00 PM CEST 
//
package com.witbooking.middleware.integration.rategain.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for HotelARIDataSetType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained
 * within this class.
 *
 * <pre>
 * &lt;complexType name="HotelARIDataSetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;choice>
 *           &lt;element name="HotelARIData" type="{http://cgbridge.rategain.com/OTA/2012/05}HotelARIDataType"/>
 *           &lt;element name="HotelARIStatus" type="{http://cgbridge.rategain.com/OTA/2012/05}HotelARIStatusType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="HotelCode" use="required" type="{http://cgbridge.rategain.com/OTA/2012/05}StringLength1to64" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HotelARIDataSetType", propOrder = {
    "hotelARIDataOrHotelARIStatus"
})
public class HotelARIDataSetType {

    private static final org.apache.log4j.Logger logger = org.apache.log4j.Logger.getLogger(HotelARIDataSetType.class);
    @XmlElements({
        @XmlElement(name = "HotelARIData", type = HotelARIDataType.class),
        @XmlElement(name = "HotelARIStatus", type = HotelARIStatusType.class)
    })
    protected List<Object> hotelARIDataOrHotelARIStatus = new ArrayList();
    @XmlAttribute(name = "HotelCode", required = true)
    protected String hotelCode;

    public HotelARIDataSetType() {
    }

    public void addHotelARIDataOrHotelARIStatus(HotelARIStatusType item) {
        if (this.hotelARIDataOrHotelARIStatus == null) {
            this.hotelARIDataOrHotelARIStatus = new ArrayList();
        }
        item.setItemIdentifier(this.hotelARIDataOrHotelARIStatus.size() + 1);
        this.hotelARIDataOrHotelARIStatus.add(item);
    }

    public void addHotelARIDataOrHotelARIStatus(HotelARIDataType item) {
        if (this.hotelARIDataOrHotelARIStatus == null) {
            this.hotelARIDataOrHotelARIStatus = new ArrayList();
        }
        final int listSize = this.hotelARIDataOrHotelARIStatus.size();
        if (item != null) {
                item.setItemIdentifier(listSize + 1);
                this.hotelARIDataOrHotelARIStatus.add(item);
        }
    }

    /**
     * Gets the value of the hotelARIDataOrHotelARIStatus property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the hotelARIDataOrHotelARIStatus property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHotelARIDataOrHotelARIStatus().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list null null null
     * null null null     {@link HotelARIDataType }
     * {@link HotelARIStatusType }
     *
     *
     */
    public List<Object> getHotelARIDataOrHotelARIStatus() {
        if (hotelARIDataOrHotelARIStatus == null) {
            hotelARIDataOrHotelARIStatus = new ArrayList<Object>();
        }
        return this.hotelARIDataOrHotelARIStatus;
    }

    /**
     * Gets the value of the hotelCode property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getHotelCode() {
        return hotelCode;
    }

    /**
     * Sets the value of the hotelCode property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setHotelCode(String value) {
        this.hotelCode = value;
    }
}
