//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.20 at 03:01:00 PM CEST 
//
package com.witbooking.middleware.integration.rategain.model;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained
 * within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Authentication" type="{http://cgbridge.rategain.com/OTA/2012/05}AuthenticationType"/>
 *         &lt;element name="HotelARIUpdateRequest">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="HotelARIData" type="{http://cgbridge.rategain.com/OTA/2012/05}HotelARIDataType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="HotelCode" use="required" type="{http://cgbridge.rategain.com/OTA/2012/05}StringLength1to64" />
 *                 &lt;attribute name="UpdateType" use="required" type="{http://cgbridge.rategain.com/OTA/2012/05}UpdateTypeType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://cgbridge.rategain.com/OTA/2012/05}MessageAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "authentication",
    "hotelARIUpdateRequest"
})
@XmlRootElement(name = "HotelARIUpdateRQ")
public class HotelARIUpdateRQ extends RateGainValidationRQInterface {

    @XmlElement(name = "Authentication", required = true)
    protected AuthenticationType authentication;
    @XmlElement(name = "HotelARIUpdateRequest", required = true)
    protected HotelARIUpdateRQ.HotelARIUpdateRequest hotelARIUpdateRequest;
    @XmlAttribute(name = "EchoToken")
    protected String echoToken;
    @XmlAttribute(name = "TimeStamp")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeStamp;
    @XmlAttribute(name = "Target")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String target;
    @XmlAttribute(name = "Version", required = true)
    protected BigDecimal version;
    @XmlAttribute(name = "TransactionIdentifier")
    protected String transactionIdentifier;

    private static final String getMSG(String name) {
        return "Property " + name + " can not be null.";
    }
    private static final String ERR_MSG_DESCRIPTION_NOT_NULL = "HotelARIDataType description update is unmanage, must be null.";

    /**
     * Gets the value of the authentication property.
     *
     * @return possible object is {@link AuthenticationType }
     *
     */
    @Override
    public AuthenticationType getAuthentication() {
        return authentication;
    }

    @Override
    protected ErrorsType validateClass() {
        ErrorsType retAcum = null;
        if (hotelARIUpdateRequest == null) {
            return new ErrorsType(ErrorType.getErrorTypeNoImplementationCodeInvalidValue(getMSG("HotelARIUpdateRequest")));
        }
        if (hotelARIUpdateRequest.getHotelCode() == null) {
            retAcum = addErrorType(retAcum, ErrorType.getErrorTypeNoImplementationCodeInvalidValue(getMSG("HotelCode")));
        }
        if (hotelARIUpdateRequest.getUpdateType() != null && !hotelARIUpdateRequest.getUpdateType().equals(UpdateTypeType.PARTIAL)) {
            retAcum = addErrorType(retAcum, ErrorType.getErrorTypeNoImplementationCodeInvalidValue(getMSG("UpdateType")));
        }
        if (!hotelARIUpdateRequest.getUpdateType().equals(UpdateTypeType.PARTIAL)) {
            retAcum = addErrorType(retAcum, ErrorType.getErrorTypeProcessingExceptionCodeUnableToProcess("UpdateType Complete unmanaged."));
        }
        if (hotelARIUpdateRequest.getHotelARIData() == null) {
            return addErrorType(retAcum, ErrorType.getErrorTypeNoImplementationCodeInvalidValue(getMSG("HotelARIData")));
        }
        for (HotelARIDataType item : hotelARIUpdateRequest.getHotelARIData()) {
            if (item == null) {
                retAcum = addErrorType(retAcum, ErrorType.getErrorTypeProcessingExceptionCodeInvalidValue(getMSG("HotelARIDataType")));
            } else {
                //Checking Description.
                //TODO hace falta implementar el update de las lineas de inventario.
                if (item.getDescription() != null){
                    retAcum = addErrorType(retAcum, ErrorType.getErrorTypeProcessingExceptionCodeInvalidValue(ERR_MSG_DESCRIPTION_NOT_NULL));
                }
                //Checking Product Reference
                if (item.getProductReference() == null) {
                    retAcum = addErrorType(retAcum, ErrorType.getErrorTypeProcessingExceptionCodeInvalidValue(getMSG("ProductReference")));
                } else if (item.getProductReference().getInvTypeCode() == null) {
                    retAcum = addErrorType(retAcum, ErrorType.getErrorTypeProcessingExceptionCodeInvalidValue(getMSG("InvTypeCode")));
                } else if (item.getProductReference().getRatePlanCode() == null) {
                    retAcum = addErrorType(retAcum, ErrorType.getErrorTypeProcessingExceptionCodeInvalidValue(getMSG("RatePlanCode")));
                }
                //Checking Applicacion Control
                if (item.getApplicationControl() == null) {
                    retAcum = addErrorType(retAcum, ErrorType.getErrorTypeProcessingExceptionCodeInvalidValue(getMSG("ApplicationControl")));
                } else {
                    retAcum = addErrorType(retAcum, item.getApplicationControl().validate());
                }
                //Checking RateAmounts
                if (item.getRateAmounts() != null) {
                    retAcum = addErrorType(retAcum, item.getRateAmounts().validate());
                }
                //Checking  Availability
                if (item.getAvailability() != null) {
                    retAcum = addErrorType(retAcum, item.getAvailability().validate());
                }
                //Checking Booking Limit
                if (item.getBookingLimit() != null) {
                    retAcum = addErrorType(retAcum,item.getBookingLimit().validate());
                }
                //Checking Booking Rules
                if (item.getBookingRules() != null){
                    retAcum = addErrorType(retAcum,item.getBookingRules().validate());
                }
            }
        }
        return retAcum;
    }

    /**
     * Sets the value of the authentication property.
     *
     * @param value allowed object is {@link AuthenticationType }
     *
     */
    public void setAuthentication(AuthenticationType value) {
        this.authentication = value;
    }

    /**
     * Gets the value of the hotelARIUpdateRequest property.
     *
     * @return possible object is
     *     {@link HotelARIUpdateRQ.HotelARIUpdateRequest }
     *
     */
    public HotelARIUpdateRQ.HotelARIUpdateRequest getHotelARIUpdateRequest() {
        return hotelARIUpdateRequest;
    }

    public List<HotelARIDataType> getHotelARIUpdateRequestHotelARIData() {
        return hotelARIUpdateRequest != null && hotelARIUpdateRequest.hotelARIData != null
                ? hotelARIUpdateRequest.hotelARIData
                : null;
    }

    public String getHotelARIUpdateRequestFirstInvTypeCode() {
        return hotelARIUpdateRequest != null
                && hotelARIUpdateRequest.getHotelARIData() != null
                && !hotelARIUpdateRequest.getHotelARIData().isEmpty()
                && hotelARIUpdateRequest.getHotelARIData().get(0) != null
                ? hotelARIUpdateRequest.getHotelARIData().get(0).getProductReferenceInvTypeCode()
                : null;
    }

    public String getHotelARIUpdateRequestFirstRatePlanCode() {
        return hotelARIUpdateRequest != null
                && hotelARIUpdateRequest.getHotelARIData() != null
                && !hotelARIUpdateRequest.getHotelARIData().isEmpty()
                && hotelARIUpdateRequest.getHotelARIData().get(0) != null
                ? hotelARIUpdateRequest.getHotelARIData().get(0).getProductReferenceRatePlanCode()
                : null;
    }

    public UpdateTypeType getHotelARIUpdateRequestUpdateType() {
        return hotelARIUpdateRequest != null ? hotelARIUpdateRequest.getUpdateType() : null;
    }

    public String getHotelARIUpdateRequestHotelTicker() {
        return hotelARIUpdateRequest != null ? hotelARIUpdateRequest.getHotelCode() : null;
    }

    /**
     * Sets the value of the hotelARIUpdateRequest property.
     *
     * @param value allowed object is
     *     {@link HotelARIUpdateRQ.HotelARIUpdateRequest }
     *
     */
    public void setHotelARIUpdateRequest(HotelARIUpdateRQ.HotelARIUpdateRequest value) {
        this.hotelARIUpdateRequest = value;
    }

    /**
     * Gets the value of the echoToken property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getEchoToken() {
        return echoToken;
    }

    /**
     * Sets the value of the echoToken property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setEchoToken(String value) {
        this.echoToken = value;
    }

    /**
     * Gets the value of the timeStamp property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setTimeStamp(XMLGregorianCalendar value) {
        this.timeStamp = value;
    }

    /**
     * Gets the value of the target property.
     *
     * @return possible object is {@link String }
     *
     */
    @Override
    public String getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setTarget(String value) {
        this.target = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    @Override
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setVersion(BigDecimal value) {
        this.version = value;
    }

    /**
     * Gets the value of the transactionIdentifier property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getTransactionIdentifier() {
        return transactionIdentifier;
    }

    /**
     * Sets the value of the transactionIdentifier property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setTransactionIdentifier(String value) {
        this.transactionIdentifier = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="HotelARIData" type="{http://cgbridge.rategain.com/OTA/2012/05}HotelARIDataType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *       &lt;attribute name="HotelCode" use="required" type="{http://cgbridge.rategain.com/OTA/2012/05}StringLength1to64" />
     *       &lt;attribute name="UpdateType" use="required" type="{http://cgbridge.rategain.com/OTA/2012/05}UpdateTypeType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hotelARIData"
    })
    public static class HotelARIUpdateRequest {

        @XmlElement(name = "HotelARIData", required = true)
        protected List<HotelARIDataType> hotelARIData;
        @XmlAttribute(name = "HotelCode", required = true)
        protected String hotelCode;
        @XmlAttribute(name = "UpdateType", required = true)
        protected UpdateTypeType updateType;

        /**
         * Gets the value of the hotelARIData property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the hotelARIData property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHotelARIData().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HotelARIDataType }
         *
         *
         */
        public List<HotelARIDataType> getHotelARIData() {
            if (hotelARIData == null) {
                hotelARIData = new ArrayList<HotelARIDataType>();
            }
            return this.hotelARIData;
        }

        /**
         * Gets the value of the hotelCode property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getHotelCode() {
            return hotelCode;
        }

        /**
         * Sets the value of the hotelCode property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setHotelCode(String value) {
            this.hotelCode = value;
        }

        /**
         * Gets the value of the updateType property.
         *
         * @return possible object is {@link UpdateTypeType }
         *
         */
        public UpdateTypeType getUpdateType() {
            return updateType;
        }

        /**
         * Sets the value of the updateType property.
         *
         * @param value allowed object is {@link UpdateTypeType }
         *
         */
        public void setUpdateType(UpdateTypeType value) {
            this.updateType = value;
        }
    }
}
