//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.20 at 03:01:00 PM CEST 
//

package com.witbooking.middleware.integration.rategain.model;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rategain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rategain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HotelARIUpdateRQ }
     * 
     */
    public HotelARIUpdateRQ createHotelARIUpdateRQ() {
        return new HotelARIUpdateRQ();
    }

    /**
     * Create an instance of {@link HotelPropertyListGetRQ }
     * 
     */
    public HotelPropertyListGetRQ createHotelPropertyListGetRQ() {
        return new HotelPropertyListGetRQ();
    }

    /**
     * Create an instance of {@link HotelARIGetRQ }
     * 
     */
    public HotelARIGetRQ createHotelARIGetRQ() {
        return new HotelARIGetRQ();
    }

    /**
     * Create an instance of {@link HotelProductListGetRQ }
     * 
     */
    public HotelProductListGetRQ createHotelProductListGetRQ() {
        return new HotelProductListGetRQ();
    }

    /**
     * Create an instance of {@link HotelARIStatusType }
     * 
     */
    public HotelARIStatusType createHotelARIStatusType() {
        return new HotelARIStatusType();
    }

    /**
     * Create an instance of {@link HotelARIDataType }
     * 
     */
    public HotelARIDataType createHotelARIDataType() {
        return new HotelARIDataType();
    }

    /**
     * Create an instance of {@link HotelARIDataType.BookingLimit }
     * 
     */
    public HotelARIDataType.BookingLimit createHotelARIDataTypeBookingLimit() {
        return new HotelARIDataType.BookingLimit();
    }

    /**
     * Create an instance of {@link HotelARIDataType.RateAmounts }
     * 
     */
    public HotelARIDataType.RateAmounts createHotelARIDataTypeRateAmounts() {
        return new HotelARIDataType.RateAmounts();
    }

    /**
     * Create an instance of {@link HotelARIDataType.RateAmounts.MealPlans }
     * 
     */
    public HotelARIDataType.RateAmounts.MealPlans createHotelARIDataTypeRateAmountsMealPlans() {
        return new HotelARIDataType.RateAmounts.MealPlans();
    }

    /**
     * Create an instance of {@link HotelProductsType }
     * 
     */
    public HotelProductsType createHotelProductsType() {
        return new HotelProductsType();
    }

    /**
     * Create an instance of {@link HotelARIGetRQ.HotelARIGetRequests }
     * 
     */
    public HotelARIGetRQ.HotelARIGetRequests createHotelARIGetRQHotelARIGetRequests() {
        return new HotelARIGetRQ.HotelARIGetRequests();
    }

    /**
     * Create an instance of {@link HotelARIUpdateRS }
     * 
     */
    public HotelARIUpdateRS createHotelARIUpdateRS() {
        return new HotelARIUpdateRS();
    }

    /**
     * Create an instance of {@link SuccessType }
     * 
     */
    public SuccessType createSuccessType() {
        return new SuccessType();
    }

    /**
     * Create an instance of {@link WarningsType }
     * 
     */
    public WarningsType createWarningsType() {
        return new WarningsType();
    }

    /**
     * Create an instance of {@link ErrorsType }
     * 
     */
    public ErrorsType createErrorsType() {
        return new ErrorsType();
    }

    /**
     * Create an instance of {@link AuthenticationType }
     * 
     */
    public AuthenticationType createAuthenticationType() {
        return new AuthenticationType();
    }

    /**
     * Create an instance of {@link HotelARIUpdateRQ.HotelARIUpdateRequest }
     * 
     */
    public HotelARIUpdateRQ.HotelARIUpdateRequest createHotelARIUpdateRQHotelARIUpdateRequest() {
        return new HotelARIUpdateRQ.HotelARIUpdateRequest();
    }

    /**
     * Create an instance of {@link HotelARIGetRS }
     * 
     */
    public HotelARIGetRS createHotelARIGetRS() {
        return new HotelARIGetRS();
    }

    /**
     * Create an instance of {@link HotelARIDataSetType }
     * 
     */
    public HotelARIDataSetType createHotelARIDataSetType() {
        return new HotelARIDataSetType();
    }

    /**
     * Create an instance of {@link HotelPropertyListGetRQ.HotelPropertyListRequest }
     * 
     */
    public HotelPropertyListGetRQ.HotelPropertyListRequest createHotelPropertyListGetRQHotelPropertyListRequest() {
        return new HotelPropertyListGetRQ.HotelPropertyListRequest();
    }

    /**
     * Create an instance of {@link HotelProductListGetRS }
     * 
     */
    public HotelProductListGetRS createHotelProductListGetRS() {
        return new HotelProductListGetRS();
    }

    /**
     * Create an instance of {@link HotelPropertyListGetRS }
     * 
     */
    public HotelPropertyListGetRS createHotelPropertyListGetRS() {
        return new HotelPropertyListGetRS();
    }

    /**
     * Create an instance of {@link HotelListType }
     * 
     */
    public HotelListType createHotelListType() {
        return new HotelListType();
    }

    /**
     * Create an instance of {@link HotelProductListGetRQ.HotelProductListRequest }
     * 
     */
    public HotelProductListGetRQ.HotelProductListRequest createHotelProductListGetRQHotelProductListRequest() {
        return new HotelProductListGetRQ.HotelProductListRequest();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link ApplicationControlType }
     * 
     */
    public ApplicationControlType createApplicationControlType() {
        return new ApplicationControlType();
    }

    /**
     * Create an instance of {@link ProductReferenceType }
     * 
     */
    public ProductReferenceType createProductReferenceType() {
        return new ProductReferenceType();
    }

    /**
     * Create an instance of {@link WarningType }
     * 
     */
    public WarningType createWarningType() {
        return new WarningType();
    }

    /**
     * Create an instance of {@link HotelType }
     * 
     */
    public HotelType createHotelType() {
        return new HotelType();
    }

    /**
     * Create an instance of {@link HotelARIStatusType.Status }
     * 
     */
    public HotelARIStatusType.Status createHotelARIStatusTypeStatus() {
        return new HotelARIStatusType.Status();
    }

    /**
     * Create an instance of {@link HotelARIDataType.Availability }
     * 
     */
    public HotelARIDataType.Availability createHotelARIDataTypeAvailability() {
        return new HotelARIDataType.Availability();
    }

    /**
     * Create an instance of {@link HotelARIDataType.BookingRules }
     * 
     */
    public HotelARIDataType.BookingRules createHotelARIDataTypeBookingRules() {
        return new HotelARIDataType.BookingRules();
    }

    /**
     * Create an instance of {@link HotelARIDataType.BookingLimit.BaseAllotment }
     * 
     */
    public HotelARIDataType.BookingLimit.BaseAllotment createHotelARIDataTypeBookingLimitBaseAllotment() {
        return new HotelARIDataType.BookingLimit.BaseAllotment();
    }

    /**
     * Create an instance of {@link HotelARIDataType.BookingLimit.TransientAllotment }
     * 
     */
    public HotelARIDataType.BookingLimit.TransientAllotment createHotelARIDataTypeBookingLimitTransientAllotment() {
        return new HotelARIDataType.BookingLimit.TransientAllotment();
    }

    /**
     * Create an instance of {@link HotelARIDataType.RateAmounts.Base }
     * 
     */
    public HotelARIDataType.RateAmounts.Base createHotelARIDataTypeRateAmountsBase() {
        return new HotelARIDataType.RateAmounts.Base();
    }

    /**
     * Create an instance of {@link HotelARIDataType.RateAmounts.Additional }
     * 
     */
    public HotelARIDataType.RateAmounts.Additional createHotelARIDataTypeRateAmountsAdditional() {
        return new HotelARIDataType.RateAmounts.Additional();
    }

    /**
     * Create an instance of {@link HotelARIDataType.RateAmounts.Discount }
     * 
     */
    public HotelARIDataType.RateAmounts.Discount createHotelARIDataTypeRateAmountsDiscount() {
        return new HotelARIDataType.RateAmounts.Discount();
    }

    /**
     * Create an instance of {@link HotelARIDataType.RateAmounts.MealPlans.MealPlan }
     * 
     */
    public HotelARIDataType.RateAmounts.MealPlans.MealPlan createHotelARIDataTypeRateAmountsMealPlansMealPlan() {
        return new HotelARIDataType.RateAmounts.MealPlans.MealPlan();
    }

    /**
     * Create an instance of {@link HotelProductsType.HotelProduct }
     * 
     */
    public HotelProductsType.HotelProduct createHotelProductsTypeHotelProduct() {
        return new HotelProductsType.HotelProduct();
    }

    /**
     * Create an instance of {@link HotelARIGetRQ.HotelARIGetRequests.HotelARIGetRequest }
     * 
     */
    public HotelARIGetRQ.HotelARIGetRequests.HotelARIGetRequest createHotelARIGetRQHotelARIGetRequestsHotelARIGetRequest() {
        return new HotelARIGetRQ.HotelARIGetRequests.HotelARIGetRequest();
    }

}
