//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.20 at 03:01:00 PM CEST 
//

package com.witbooking.middleware.integration.rategain.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OccupancyCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OccupancyCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="A1"/>
 *     &lt;enumeration value="A2"/>
 *     &lt;enumeration value="A2C1"/>
 *     &lt;enumeration value="A2C2"/>
 *     &lt;enumeration value="A3"/>
 *     &lt;enumeration value="A4"/>
 *     &lt;enumeration value="AA"/>
 *     &lt;enumeration value="AC"/>
 *     &lt;enumeration value="EB"/>
 *     &lt;enumeration value="BC"/>
 *     &lt;enumeration value="SF"/>
 *     &lt;enumeration value="SX"/>
 *     &lt;enumeration value="SR"/>
 *     &lt;enumeration value="X1"/>
 *     &lt;enumeration value="X2"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OccupancyCodeType")
@XmlEnum
public enum OccupancyCodeType {

    @XmlEnumValue("A1")
    A_1("A1"),
    @XmlEnumValue("A2")
    A_2("A2"),
    @XmlEnumValue("A2C1")
    A_2_C_1("A2C1"),
    @XmlEnumValue("A2C2")
    A_2_C_2("A2C2"),
    @XmlEnumValue("A3")
    A_3("A3"),
    @XmlEnumValue("A4")
    A_4("A4"),
    AA("AA"),
    AC("AC"),
    EB("EB"),
    BC("BC"),
    SF("SF"),
    SX("SX"),
    @XmlEnumValue("SR")
    SR("SR"),
    @XmlEnumValue("X1")
    X_1("X1"),
    @XmlEnumValue("X2")
    X_2("X2");
    private final String value;

    OccupancyCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OccupancyCodeType fromValue(String v) {
        for (OccupancyCodeType c: OccupancyCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
