//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.20 at 03:01:00 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://cgbridge.rategain.com/OTA/2012/05", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.witbooking.middleware.integration.rategain.model;
