//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.28 at 02:33:51 PM CEST 
//


package com.witbooking.middleware.integration.ota.model;

import com.google.common.base.Objects;
import com.witbooking.middleware.integration.rategain.ConstantsRateGain;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for ErrorType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="ErrorType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.opentravel.org/OTA/2003/05>FreeTextType">
 *       &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05}ErrorWarningAttributeGroup"/>
 *       &lt;attribute name="Type" use="required" type="{http://www.opentravel.org/OTA/2003/05}OTA_CodeType" />
 *       &lt;attribute name="NodeList" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ErrorType")
public class ErrorType
        extends FreeTextType {

    @XmlAttribute(name = "Type", required = true)
    protected String type;
    @XmlAttribute(name = "NodeList")
    protected String nodeList;
    @XmlAttribute(name = "ShortText")
    protected String shortText;
    @XmlAttribute(name = "Code")
    protected String code;
    @XmlAttribute(name = "DocURL")
    @XmlSchemaType(name = "anyURI")
    protected String docURL;
    @XmlAttribute(name = "Status")
    protected String status;
    @XmlAttribute(name = "Tag")
    protected String tag;
    @XmlAttribute(name = "RecordID")
    protected String recordID;

    public ErrorType() {
    }

    public ErrorType(String type, String code, String value) {
        this.type = type;
        this.code = code;
        this.value = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the nodeList property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNodeList() {
        return nodeList;
    }

    /**
     * Sets the value of the nodeList property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNodeList(String value) {
        this.nodeList = value;
    }

    /**
     * Gets the value of the shortText property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getShortText() {
        return shortText;
    }

    /**
     * Sets the value of the shortText property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setShortText(String value) {
        this.shortText = value;
    }

    /**
     * Gets the value of the code property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the docURL property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDocURL() {
        return docURL;
    }

    /**
     * Sets the value of the docURL property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDocURL(String value) {
        this.docURL = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the tag property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTag() {
        return tag;
    }

    /**
     * Sets the value of the tag property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTag(String value) {
        this.tag = value;
    }

    /**
     * Gets the value of the recordID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRecordID() {
        return recordID;
    }

    /**
     * Sets the value of the recordID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRecordID(String value) {
        this.recordID = value;
    }

    /**
     * @return <code>ErrorType</code> Object with type
     * {@link ConstantsRateGain.Error.Type#UNKNOWN} without error code.
     */
    public static ErrorType getUnableToProcess() {
        ErrorType error = new ErrorType();
        error.setType(ConstantsRateGain.Error.Type.UNKNOWN);
        error.setCode(ConstantsRateGain.Error.Code.UNABLE_TO_PROCESS);
        return error;
    }


    public static ErrorType getUnableToProcess(String message) {
        ErrorType error = getUnableToProcess();
        error.setShortText(message);
        error.setStatus("NotProcessed");
        return error;
    }

    public static ErrorType getSoapFault(SoapFault soapFault) {
        ErrorType error = new ErrorType();
        error.setType(ConstantsRateGain.Error.Type.PROTOCOL_VIOLATION);
        error.setCode(ConstantsRateGain.Error.Code.UNABLE_TO_PROCESS);
        error.setShortText(soapFault.faultCode + " - " + soapFault.faultText);
        error.setStatus("NotProcessed");
        return error;
    }

    @Override
    public String toString() {
        return Objects.toStringHelper(this)
                .add("type", type)
                .add("nodeList", nodeList)
                .add("shortText", shortText)
                .add("code", code)
                .add("docURL", docURL)
                .add("status", status)
                .add("tag", tag)
                .add("recordID", recordID)
                .add("value", value)
                .add("language", language)
                .toString();
    }
}
