//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.28 at 02:33:51 PM CEST 
//


package com.witbooking.middleware.integration.ota.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for POS_Type complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="POS_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Source" type="{http://www.opentravel.org/OTA/2003/05}SourceType" maxOccurs="10"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POS_Type", propOrder = {
        "source"
})
public class POSType {

    @XmlElement(name = "Source", required = true)
    protected List<SourceType> source;

    public POSType() {
    }

    /**
     * @param userId      Pos.source.requestorId.id
     * @param channelId   pos.source.boookingChannel.companyName.type
     * @param channelName pos.source.bookingChannel.companyName
     */
    public POSType(final String userId, final String channelId, final String channelName) {
        this.source = new ArrayList<SourceType>();
        this.source.add(new SourceType(userId, channelId, channelName));
    }

    /**
     * Gets the value of the source property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the source property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSource().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link SourceType }
     */
    public List<SourceType> getSource() {
        if (source == null) {
            source = new ArrayList<SourceType>();
        }
        return this.source;
    }

    @Override
    public String toString() {
        String ret = "POSType{" +
                "source=[";
        if (source != null && !source.isEmpty()) {
            for (final SourceType sourceType : source) {
                ret += sourceType + " ,";
            }
            ret = ret.substring(0, ret.length() - 2);
        }
        ret += "] }";
        return ret;
    }
}
